MODEL:
  META_ARCHITECTURE: "MGMMaskFormer"
  BACKBONE:
    FREEZE_AT: 0
    NAME: "D2SwinTransformer"
  
  # Depth Backbone Configuration
  DEPTH_BACKBONE:
    NAME: "ConvNeXtDepthBackbone"
    WEIGHTS: ""
    DEPTHS: [3, 3, 9, 3]
    DIMS: [96, 192, 384, 768]
    DROP_PATH: 0.0
    LAYER_SCALE: 1e-6
  
  # MGM Fusion Configuration
  MGM:
    FUSION_TYPE: "attention"
    FUSION_DIM: 256
    NUM_FUSION_LAYERS: 3
  
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  
DATASETS:
  TRAIN: ("coco_instance_train_rgbd",)
  TEST: ("coco_instance_val_rgbd",)
  
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.0001
  STEPS: (327778, 355092)
  MAX_ITER: 368750
  WARMUP_FACTOR: 1.0
  WARMUP_ITERS: 10
  WEIGHT_DECAY: 0.05
  OPTIMIZER: "ADAMW"
  BACKBONE_MULTIPLIER: 0.1
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 0.01
    NORM_TYPE: 2.0
  AMP:
    ENABLED: True
    
INPUT:
  IMAGE_SIZE: 1024
  MIN_SCALE: 0.1
  MAX_SCALE: 2.0
  FORMAT: "RGB"
  DATASET_MAPPER_NAME: "coco_instance_lsj_rgbd"
  
TEST:
  EVAL_PERIOD: 5000
  
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True
  NUM_WORKERS: 4
  
VERSION: 2