MODEL:
  META_ARCHITECTURE: "MGMMaskFormer"
  FINETUNE_WEIGHTS: ""

  # RGB Backbone: Swin Transformer Tiny
  RGB_BACKBONE:
    NAME: "D2SwinTransformer"
    WEIGHTS: ""
    SWIN:
      EMBED_DIM: 96
      DEPTHS: [2, 2, 6, 2]
      NUM_HEADS: [3, 6, 12, 24]
      WINDOW_SIZE: 7
      APE: False
      DROP_PATH_RATE: 0.3
      PATCH_NORM: True
      OUT_FEATURES: ["res2", "res3", "res4", "res5"]

  # Depth Backbone: ConvNeXt Tiny
  DEPTH_BACKBONE:
    NAME: "ConvNeXtDepthBackbone"
    WEIGHTS: ""
    CONVNEXT:
      DEPTHS: [3, 3, 9, 3]
      DIMS: [96, 192, 384, 768]
      DROP_PATH_RATE: 0.0
      LAYER_SCALE: 1e-6

  # MGM Fusion Configuration
  MGM:
    ENABLED: True
    SHARED: True
    RESIDUAL_ALPHA: 0.05
    POST_FUSE_NORM: True
    LOSS_ENTROPY_W: 0.0
    TEMP_INIT: 2.0
    TEMP_FINAL: 1.0
    TEMP_STEPS: 5000
    CLAMP_MIN: 0.05
    CLAMP_MAX: 0.95
    NOISE_MASK_WEIGHT: 0.0
    HIDDEN_DIM: 256
    FEATURE_DIMS: [96, 192, 384, 768]
    SCALE_KEYS: ["res2", "res3", "res4", "res5"]

    PRIOR:
      ENABLED: True # 总开关
      USE_GRADIENT: True # 先验逐项开关
      USE_VARIANCE: True
      USE_VALID_HOLE: True
      USE_RGB_EDGE: False # 前期建议关（最耗时）
      VAR_KERNEL: 5
      Z_MIN: 0.0
      Z_MAX: 1.0
      COMPUTE_ON: "res3" # "full"|"res2"|"res3"|"res4"|"res5"；前期建议用res3提速

    ROBUST_NORM:
      ENABLED: False # 前期建议关；要稳健再开
      METHOD: "minmax" # "minmax"|"quantile"

  # DPE Configuration
  DPE:
    ENABLED: True

  # Boundary Configuration
  BOUNDARY:
    ENABLED: False

  # RGB Input Pixel Mean/Std
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]

  # Semantic Segmentation Head
  SEM_SEG_HEAD:
    NAME: "MGMHead"
    IGNORE_VALUE: 255
    NUM_CLASSES: 1
    LOSS_WEIGHT: 1.0
    CONVS_DIM: 256
    MASK_DIM: 256
    NORM: "GN"
    PIXEL_DECODER_NAME: "MGMMSDeformAttnPixelDecoder"
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
    DEFORMABLE_TRANSFORMER_ENCODER_IN_FEATURES: ["res3", "res4", "res5"]
    DEFORMABLE_TRANSFORMER_ENCODER_N_POINTS: 4
    DEFORMABLE_TRANSFORMER_ENCODER_N_HEADS: 8
    COMMON_STRIDE: 4
    TRANSFORMER_ENC_LAYERS: 6

  MASK_FORMER:
    TRANSFORMER_DECODER_NAME: "MGMMultiScaleMaskedTransformerDecoder"
    TRANSFORMER_IN_FEATURE: "multi_scale_pixel_decoder"
    DEEP_SUPERVISION: True
    NO_OBJECT_WEIGHT: 0.1
    CLASS_WEIGHT: 2.0
    MASK_WEIGHT: 5.0
    DICE_WEIGHT: 5.0
    HIDDEN_DIM: 256
    NUM_OBJECT_QUERIES: 100
    NHEADS: 8
    DROPOUT: 0.0
    DIM_FEEDFORWARD: 2048
    ENC_LAYERS: 0
    DEC_LAYERS: 10
    PRE_NORM: False
    ENFORCE_INPUT_PROJ: False
    SIZE_DIVISIBILITY: 32
    TRAIN_NUM_POINTS: 16384
    OVERSAMPLE_RATIO: 3.0
    IMPORTANCE_SAMPLE_RATIO: 0.75
    TEST:
      SEMANTIC_ON: False
      INSTANCE_ON: True
      PANOPTIC_ON: False
      OVERLAP_THRESHOLD: 0.8
      OBJECT_MASK_THRESHOLD: 0.8

# 数据集配置
DATASETS:
  TRAIN: ("coco_instance_rgbd_train",)
  TEST: ("coco_instance_rgbd_val",)

# 数据加载器配置
DATALOADER:
  NUM_WORKERS: 16
  ASPECT_RATIO_GROUPING: True
  FILTER_EMPTY_ANNOTATIONS: True
  REPEAT_THRESHOLD: 0.0

  # RGB-D Input Configuration - 快速训练模式
INPUT:
  DATASET_ROOT: "/home/fuyx/zhn/mgm_datasets/output_multi_0.001_novis_10p"
  IMAGE_SIZE: 1024
  MIN_SCALE: 0.8
  MAX_SCALE: 1.2
  FORMAT: "RGB"
  DATASET_MAPPER_NAME: "coco_instance_lsj_rgbd"
  RANDOM_FLIP: "horizontal"
  SIZE_DIVISIBILITY: 32

  # RGB光度增强
  RGB_PHOTO_AUG:
    ENABLED: False
    BRIGHTNESS: 0.2
    CONTRAST: 0.2
    SATURATION: 0.1
    HUE: 0.0

  # 深度数据配置
  DEPTH_FORMAT: "I"
  DEPTH_SCALE: 0.001
  DEPTH_SHIFT: 0.0
  DEPTH_CLIP_MIN: 0.0
  DEPTH_CLIP_MAX: 1.0
  DEPTH_NORM: "minmax"
  DEPTH_NOISE:
    ENABLED: True
    GAUSSIAN_STD: 0.05
    SPECKLE_STD: 0.0
    DROP_PROB: 0.05
    DROP_VAL: 0.0

# 求解器配置
SOLVER:
  IMS_PER_BATCH: 1
  BASE_LR: 5e-5
  STEPS: (8000, 9000)
  MAX_ITER: 10000
  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 2000
  WARMUP_METHOD: linear
  GAMMA: 0.1
  OPTIMIZER: ADAMW
  BACKBONE_MULTIPLIER: 0.1
  WEIGHT_DECAY: 0.05
  WEIGHT_DECAY_NORM: 0.0
  WEIGHT_DECAY_EMBED: 0.0
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 1.0
    NORM_TYPE: 2.0
  AMP:
    ENABLED: True

# 测试配置
TEST:
  EVAL_PERIOD: 1000
  AUG:
    ENABLED: False

# 输出配置
OUTPUT_DIR: "./output/2k_0831"

# 版本号
VERSION: 2.0
